import { useEffect, useState } from 'react';
import { Helmet } from 'react-helmet-async';
import db from '@/lib/shared/kliv-database.js';

export default function SitemapProxy() {
  const [sitemap, setSitemap] = useState<string>('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const generateSitemap = async () => {
      console.log('SitemapProxy: Starting to generate sitemap from database');
      try {
        const BASE_URL = 'https://kliv.kliv.site'; // Use the staging domain
        const currentDate = new Date().toISOString().split('T')[0];

        // Query categories and pages directly from database
        const categories = await db.query('landing_categories', {}, 'select=slug');
        const pages = await db.query('landing_pages', {}, 'select=slug,category_name');

        console.log('SitemapProxy: Got categories:', categories.length, 'pages:', pages.length);

        let sitemapXml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated dynamically by SitemapProxy (DB query) at ${new Date().toISOString()} -->
<!-- Categories found: ${categories.length}, Pages found: ${pages.length} -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">`;

        // Add static pages
        const staticPages = ['', 'about', 'features', 'pricing', 'careers', 'privacy', 'terms', 'security', 'signup', 'login', 'inspiration'];
        const languages = ['en', 'ja', 'sv'];

        languages.forEach(lang => {
          staticPages.forEach(page => {
            const url = page === '' ? `${BASE_URL}/${lang}` : `${BASE_URL}/${lang}/${page}`;
            const priority = page === '' ? '1.0' : '0.8';
            sitemapXml += `
  <url>
    <loc>${url}</loc>
    <lastmod>${currentDate}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>${priority}</priority>
  </url>`;
          });
        });

        // Add category pages
        categories.forEach((category: any) => {
          languages.forEach(lang => {
            const url = `${BASE_URL}/${lang}/inspiration/${category.slug}`;
            sitemapXml += `
  <url>
    <loc>${url}</loc>
    <lastmod>${currentDate}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>`;
          });
        });

        // Add landing pages
        pages.forEach((page: any) => {
          const categorySlug = page.category_name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
          languages.forEach(lang => {
            const url = `${BASE_URL}/${lang}/${categorySlug}/${page.slug}`;
            sitemapXml += `
  <url>
    <loc>${url}</loc>
    <lastmod>${currentDate}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>`;
          });
        });

        const totalUrls = (staticPages.length * languages.length) + (categories.length * languages.length) + (pages.length * languages.length);
        sitemapXml += `
<!-- Total URLs: ${totalUrls} -->
</urlset>`;

        console.log('SitemapProxy: Generated sitemap, length:', sitemapXml.length);
        console.log('SitemapProxy: First 200 chars:', sitemapXml.substring(0, 200));
        setSitemap(sitemapXml);

      } catch (error) {
        console.error('SitemapProxy: Failed to generate sitemap from database:', error);
        
        // Fallback to minimal sitemap with verification comment
        const currentDate = new Date().toISOString().split('T')[0];
        const fallbackSitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by SitemapProxy fallback component at ${new Date().toISOString()} -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://kliv.kliv.site/</loc>
    <lastmod>${currentDate}</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>
</urlset>`;
        setSitemap(fallbackSitemap);
      } finally {
        setLoading(false);
      }
    };

    generateSitemap();
  }, []);

  if (loading) {
    console.log('SitemapProxy: Still loading...');
    return null;
  }

  console.log('SitemapProxy: Rendering sitemap, content length:', sitemap.length);

  // Set the content type and render the XML directly
  return (
    <>
      <Helmet>
        <title>Sitemap</title>
        <meta httpEquiv="Content-Type" content="application/xml; charset=utf-8" />
      </Helmet>
      <div
        style={{
          background: 'white',
          color: 'black',
          padding: '20px',
          fontFamily: 'monospace',
          whiteSpace: 'pre-wrap',
          fontSize: '12px'
        }}
      >
        {sitemap}
      </div>
    </>
  );
}