import { useEffect, useState } from 'react';
import { Helmet } from 'react-helmet-async';

export default function SitemapProxy() {
  const [sitemap, setSitemap] = useState<string>('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchSitemap = async () => {
      console.log('SitemapProxy: Starting to fetch sitemap from edge function');
      try {
        // Try to fetch from edge function
        const response = await fetch('/api/v2/functions/sitemap');
        console.log('SitemapProxy: Edge function response status:', response.status);
        
        if (response.ok) {
          const sitemapXml = await response.text();
          console.log('SitemapProxy: Successfully fetched sitemap, length:', sitemapXml.length);
          setSitemap(sitemapXml);
        } else {
          throw new Error(`Edge function failed with status ${response.status}`);
        }
      } catch (error) {
        console.error('SitemapProxy: Failed to fetch from edge function:', error);
        
        // Fallback to minimal sitemap with verification comment
        const currentDate = new Date().toISOString().split('T')[0];
        const fallbackSitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by SitemapProxy fallback component at ${new Date().toISOString()} -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://kliv.dev/</loc>
    <lastmod>${currentDate}</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>https://kliv.dev/en</loc>
    <lastmod>${currentDate}</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>https://kliv.dev/en/inspiration</loc>
    <lastmod>${currentDate}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
</urlset>`;
        setSitemap(fallbackSitemap);
      } finally {
        setLoading(false);
      }
    };

    fetchSitemap();
  }, []);

  if (loading) {
    console.log('SitemapProxy: Still loading...');
    return null;
  }

  console.log('SitemapProxy: Rendering sitemap, content length:', sitemap.length);

  // Set the content type and render the XML directly
  return (
    <>
      <Helmet>
        <title>Sitemap</title>
        <meta httpEquiv="Content-Type" content="application/xml; charset=utf-8" />
      </Helmet>
      <div
        style={{
          background: 'white',
          color: 'black',
          padding: '20px',
          fontFamily: 'monospace',
          whiteSpace: 'pre-wrap',
          fontSize: '12px'
        }}
      >
        {sitemap}
      </div>
    </>
  );
}